# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f545219cd49671d5c8504437e4cc07aabe303e31293ee91e6dad51bd981071e0004abba6df72a00f9b5d8683199a97c9e0abac29f42ee057b721b2a29575332

test:
  secret_key_base: b5b414148416f79a9c4cd449f90cadf3075a83aad43739b494f41d42cf68b2e88f774417eee46c9864bef3e29f9f9c4733c7b5def2b415624e775093bd08a02d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
